### ISSUE TITLE
[Question] Interested in collaborating with another multi-agent RL project?

### ISSUE THREAD

**Issue by GunnarZarncke** [doesburg11/PredPreyGrass#3]
### Question

Hi doesburg11,

your multi-agent RL project is very close to what the aintelope team ist building too. Our purpose is not to reproduce natural dynamics but eventually pro-social behaviors. If that's interesting, feel free to get in touch with me g dot zarncke at gmail. 

https://www.aintelope.net/

best
Gunnar

PS. I'm raising this as an issue because I can't find any other contact information.

**Comment by doesburg11** [comment]
Closed as contact is established.
